### Registrar un Usuario#####
POST http://localhost:5000/users/register
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "password123"
}

### Iniciar sesión
POST http://localhost:5000/users/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "password123"
}


### Crear un Grupo
POST http://localhost:5000/groups/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjc1MzBlN2QxYTk2NGU2N2JjODk1NmQ5IiwiZW1haWwiOiJqb2huLmRvZUBleGFtcGxlLmNvbSIsImV4cCI6MTczMzYwMDExM30.Y47ggDiga1VEmpTakfCyBoW4GxmUfvCl3DnGVDwFM9k

{
  "name": "Viaje con Amigos",
  "members": ["Alice", "Bob", "Charlie"]
}
